---

## Start Preconditions for the ruby role
- name: check base commands are presente
  become: yes
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - curl
    - tar

- name: install which
  become: yes
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - which
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: install dirmngr
  become: yes
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - dirmngr
    - build-essential
    - libcurl
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

## End Preconditions for the ruby role

- name: install ruby
  include_role:
    name: rvm_io.ruby
  vars:
    rvm1_rubies: ['{{ ruby_version }}']
    rvm1_install_flags: '--auto-dotfiles'     # Remove --user-install from defaults
    rvm1_install_path: "{{ruby_install_path}}"         # Set to system location
    rvm1_user: root                            # Need root account to access system location

- name: Install gem dependencies
  #become: yes
  gem:
    name: "jekyll"
    state: latest
    user_install: no
  register: jekyllinstall
