---

- name: install the latest ruby dependencies for jekyll
  become: yes
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - rubygems
    - ruby-full
    - ruby-dev
    - build-essential

- name: Install gem dependencies
  gem:
    name: "{{item}}"
    state: latest
  with_items:
    - bundler
    - jekyll
