---


- name: missing on centos6 ...
  package:
    name: "tar"
    state: latest

- name: install ruby
  include_role:
    name: geerlingguy.ruby
  vars:
    ruby_install_from_source: true
    ruby_install_gems:
      - jekyll
