---

- debug:
    msg: "Ansible Host {{ ansible_hostname }} with {{ansible_os_family}} version {{ansible_distribution_version}}"

- name: install the latest version of ruby
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - ruby
    - rubygems

- gem:
    name: "{{item}}"
    state: latest
  with_items:
    - jekyll
    - bundler
